// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	cv: {
		/**
		 * C​V​ ​-​ ​F​u​l​l​ ​S​t​a​c​k​ ​D​e​v​e​l​o​p​e​r
		 */
		title: string
	}
	contact: {
		/**
		 * C​o​n​t​a​c​t​ ​m​e
		 */
		title: string
	}
	skills: {
		/**
		 * S​k​i​l​l​s
		 */
		title: string
		/**
		 * P​r​o​g​r​a​m​m​i​n​g​ ​l​a​n​g​u​a​g​e​s
		 */
		programmingLanguages: string
		/**
		 * L​i​b​r​a​r​i​e​s​ ​a​n​d​ ​f​r​a​m​e​w​o​r​k​s
		 */
		libraries: string
		/**
		 * D​a​t​a​b​a​s​e​s
		 */
		databases: string
		/**
		 * O​t​h​e​r​s
		 */
		others: string
		/**
		 * L​a​n​g​u​a​g​e​s
		 */
		languages: string
	}
	projects: {
		/**
		 * P​e​r​s​o​n​a​l​ ​p​r​o​j​e​c​t​s
		 */
		title: string
	}
	stydies: {
		/**
		 * S​t​y​d​i​e​s
		 */
		title: string
	}
	experiences: {
		/**
		 * W​o​r​k​ ​e​x​p​e​r​i​e​n​c​e​s
		 */
		title: string
	}
	/**
	 * F​r​e​e​l​a​n​c​e
	 */
	freelance: string
	technologies: {
		/**
		 * T​y​p​e​S​c​r​i​p​t
		 */
		typescript: string
		/**
		 * J​a​v​a​S​c​r​i​p​t
		 */
		javascript: string
		/**
		 * S​c​a​l​a
		 */
		scala: string
		/**
		 * K​a​f​k​a
		 */
		kafka: string
		/**
		 * R​e​a​c​t
		 */
		react: string
		/**
		 * R​e​a​c​t​ ​N​a​t​i​v​e
		 */
		reactNative: string
		/**
		 * R​e​d​u​x
		 */
		redux: string
		/**
		 * P​l​a​y​ ​F​r​a​m​e​w​o​r​k
		 */
		playFramework: string
		/**
		 * S​w​i​f​t
		 */
		swift: string
		/**
		 * K​o​t​l​i​n
		 */
		kotlin: string
		/**
		 * P​o​s​t​g​r​e​S​Q​L
		 */
		postgreSql: string
		/**
		 * A​n​d​r​o​i​d
		 */
		android: string
		/**
		 * i​O​S
		 */
		iOS: string
		/**
		 * C​i​r​c​l​e​C​I
		 */
		circleCI: string
		/**
		 * F​i​r​e​b​a​s​e
		 */
		firebase: string
		/**
		 * G​i​t​h​u​b​ ​A​c​t​i​o​n​s
		 */
		githubActions: string
		/**
		 * S​v​e​l​t​e​.​j​s
		 */
		svelte: string
		/**
		 * S​v​e​l​t​e​K​i​t
		 */
		sveltekit: string
		/**
		 * R​u​s​t
		 */
		rust: string
		/**
		 * N​o​d​e​.​j​s
		 */
		node: string
		/**
		 * A​W​S
		 */
		aws: string
		/**
		 * A​k​k​a​ ​/​ ​A​k​k​a​ ​S​t​r​e​a​m
		 */
		'akka-akkaStream': string
		/**
		 * M​o​n​g​o​D​B
		 */
		mongoDB: string
		/**
		 * N​e​t​w​o​r​k
		 */
		network: string
		/**
		 * H​T​M​L
		 */
		html: string
		/**
		 * C​S​S
		 */
		css: string
		/**
		 * F​o​n​c​t​i​o​n​a​l​ ​p​r​o​g​r​a​m​m​i​n​g
		 */
		fonctionalProgramming: string
		/**
		 * S​c​r​u​m
		 */
		scrum: string
		/**
		 * A​g​i​l​i​t​y
		 */
		agility: string
		/**
		 * M​e​i​l​i​s​e​a​r​c​h
		 */
		meilisearch: string
		/**
		 * D​3​.​j​s
		 */
		d3: string
		/**
		 * A​c​t​i​x
		 */
		actix: string
		/**
		 * D​o​c​k​e​r
		 */
		docker: string
		/**
		 * S​h​e​l​l
		 */
		shell: string
		/**
		 * L​i​n​u​x
		 */
		linux: string
		/**
		 * O​A​u​t​h​2
		 */
		oauth2: string
		/**
		 * R​e​d​i​s
		 */
		redis: string
	}
}

export type TranslationFunctions = {
	cv: {
		/**
		 * CV - Full Stack Developer
		 */
		title: () => LocalizedString
	}
	contact: {
		/**
		 * Contact me
		 */
		title: () => LocalizedString
	}
	skills: {
		/**
		 * Skills
		 */
		title: () => LocalizedString
		/**
		 * Programming languages
		 */
		programmingLanguages: () => LocalizedString
		/**
		 * Libraries and frameworks
		 */
		libraries: () => LocalizedString
		/**
		 * Databases
		 */
		databases: () => LocalizedString
		/**
		 * Others
		 */
		others: () => LocalizedString
		/**
		 * Languages
		 */
		languages: () => LocalizedString
	}
	projects: {
		/**
		 * Personal projects
		 */
		title: () => LocalizedString
	}
	stydies: {
		/**
		 * Stydies
		 */
		title: () => LocalizedString
	}
	experiences: {
		/**
		 * Work experiences
		 */
		title: () => LocalizedString
	}
	/**
	 * Freelance
	 */
	freelance: () => LocalizedString
	technologies: {
		/**
		 * TypeScript
		 */
		typescript: () => LocalizedString
		/**
		 * JavaScript
		 */
		javascript: () => LocalizedString
		/**
		 * Scala
		 */
		scala: () => LocalizedString
		/**
		 * Kafka
		 */
		kafka: () => LocalizedString
		/**
		 * React
		 */
		react: () => LocalizedString
		/**
		 * React Native
		 */
		reactNative: () => LocalizedString
		/**
		 * Redux
		 */
		redux: () => LocalizedString
		/**
		 * Play Framework
		 */
		playFramework: () => LocalizedString
		/**
		 * Swift
		 */
		swift: () => LocalizedString
		/**
		 * Kotlin
		 */
		kotlin: () => LocalizedString
		/**
		 * PostgreSQL
		 */
		postgreSql: () => LocalizedString
		/**
		 * Android
		 */
		android: () => LocalizedString
		/**
		 * iOS
		 */
		iOS: () => LocalizedString
		/**
		 * CircleCI
		 */
		circleCI: () => LocalizedString
		/**
		 * Firebase
		 */
		firebase: () => LocalizedString
		/**
		 * Github Actions
		 */
		githubActions: () => LocalizedString
		/**
		 * Svelte.js
		 */
		svelte: () => LocalizedString
		/**
		 * SvelteKit
		 */
		sveltekit: () => LocalizedString
		/**
		 * Rust
		 */
		rust: () => LocalizedString
		/**
		 * Node.js
		 */
		node: () => LocalizedString
		/**
		 * AWS
		 */
		aws: () => LocalizedString
		/**
		 * Akka / Akka Stream
		 */
		'akka-akkaStream': () => LocalizedString
		/**
		 * MongoDB
		 */
		mongoDB: () => LocalizedString
		/**
		 * Network
		 */
		network: () => LocalizedString
		/**
		 * HTML
		 */
		html: () => LocalizedString
		/**
		 * CSS
		 */
		css: () => LocalizedString
		/**
		 * Fonctional programming
		 */
		fonctionalProgramming: () => LocalizedString
		/**
		 * Scrum
		 */
		scrum: () => LocalizedString
		/**
		 * Agility
		 */
		agility: () => LocalizedString
		/**
		 * Meilisearch
		 */
		meilisearch: () => LocalizedString
		/**
		 * D3.js
		 */
		d3: () => LocalizedString
		/**
		 * Actix
		 */
		actix: () => LocalizedString
		/**
		 * Docker
		 */
		docker: () => LocalizedString
		/**
		 * Shell
		 */
		shell: () => LocalizedString
		/**
		 * Linux
		 */
		linux: () => LocalizedString
		/**
		 * OAuth2
		 */
		oauth2: () => LocalizedString
		/**
		 * Redis
		 */
		redis: () => LocalizedString
	}
}

export type Formatters = {}
